import type { Metadata } from 'next'
import Link from 'next/link'
import { FriendCard } from '@/components/friends/friend-card'
import { getFriendCategories, getPublicFriends } from '@/lib/friends'

export const metadata: Metadata = { title: 'Friends — QNotables', description: 'Trusted communities, creators, organizations, and websites recommended by QNotables.' }

export default async function FriendsPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; sort?: string }> }) {
  const params = await searchParams
  const [friends, categories] = await Promise.all([getPublicFriends({ search: params.q, category: params.category, sort: params.sort }), getFriendCategories()])
  const featured = friends.filter((friend) => friend.featured)
  const directory = friends.filter((friend) => !friend.featured)
  return <main className="mx-auto flex max-w-7xl flex-col gap-10 px-4 py-12 md:px-8"><header className="max-w-3xl"><p className="label-mono text-primary">QNOTABLES COMMUNITY</p><h1 className="stencil mt-2 text-4xl md:text-5xl">Friends</h1><p className="mt-4 text-base leading-7 text-muted-foreground">A considered directory of people, projects, and places we trust. Want to be included? <Link href="/friends/submit" className="text-primary underline">Submit a Friend</Link>.</p></header><form className="grid gap-3 border-y border-border py-4 md:grid-cols-[1fr_220px_180px_auto]"><input name="q" defaultValue={params.q} placeholder="Search Friends" className="border border-input bg-background px-3 py-2 text-sm text-foreground" /><select name="category" defaultValue={params.category} className="border border-input bg-background px-3 py-2 text-sm text-foreground"><option value="">All categories</option>{categories.map((category) => <option key={category.slug} value={category.slug}>{category.name}</option>)}</select><select name="sort" defaultValue={params.sort ?? 'featured'} className="border border-input bg-background px-3 py-2 text-sm text-foreground"><option value="featured">Featured first</option><option value="newest">Newest</option><option value="alphabetical">Alphabetical</option></select><button className="bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Filter</button></form>{featured.length > 0 && <section><div className="mb-4 flex items-end justify-between"><div><p className="label-mono text-primary">SELECTED SIGNALS</p><h2 className="stencil mt-1 text-2xl">Featured Friends</h2></div><span className="text-sm text-muted-foreground">{featured.length} listings</span></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{featured.map((friend) => <FriendCard key={friend.id} friend={friend} />)}</div></section>}<section><div className="mb-4 flex items-end justify-between"><div><p className="label-mono text-primary">THE DIRECTORY</p><h2 className="stencil mt-1 text-2xl">All Friends</h2></div><span className="text-sm text-muted-foreground">{directory.length + featured.length} approved</span></div>{friends.length === 0 ? <div className="border border-dashed border-border p-10 text-center"><p className="stencil text-xl">Nothing matched that search</p><p className="mt-2 text-sm text-muted-foreground">Try a different name, domain, or category.</p></div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{directory.map((friend) => <FriendCard key={friend.id} friend={friend} />)}</div>}</section></main>
}
