import { redirect } from 'next/navigation'
import { getAdminUser } from '@/lib/admin'
import { createAdminClient } from '@/lib/supabase/admin'
import { addAllowedFriendDomain, removeAllowedFriendDomain, updateFriendSettings } from '@/app/dashboard/friends/actions'

export default async function FriendsSettingsPage() {
  if (!await getAdminUser()) redirect('/dashboard/login')
  const client = createAdminClient()
  const [{ data: settings }, { data: domains }] = await Promise.all([
    client.from('friend_settings').select('max_submissions_per_user, require_allowed_domain').eq('id', 1).maybeSingle(),
    client.from('friend_allowed_domains').select('domain, is_active').order('domain'),
  ])
  return <main className="mx-auto flex max-w-3xl flex-col gap-6 px-4 py-10"><div><p className="label-mono text-primary">FRIENDS CONTROL</p><h1 className="stencil mt-1 text-3xl">Directory settings</h1><p className="mt-2 text-sm text-muted-foreground">Set submission guardrails and maintain the optional allowed-domain list.</p></div><section className="border border-border bg-card p-5"><h2 className="stencil text-xl">Submission rules</h2><form action={updateFriendSettings} className="mt-5 flex flex-col gap-4"><label className="flex flex-col gap-2 text-sm"><span className="label-mono text-xs text-muted-foreground">Maximum submissions per user</span><input name="max_submissions_per_user" type="number" min="1" max="100" defaultValue={settings?.max_submissions_per_user ?? 5} className="w-32 border border-input bg-background px-3 py-2 text-foreground" /></label><label className="flex items-center gap-3 text-sm text-muted-foreground"><input name="require_allowed_domain" type="checkbox" defaultChecked={settings?.require_allowed_domain ?? false} className="accent-primary" /> Require submitted domains to be on the allowlist</label><button className="w-fit bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Save settings</button></form></section><section className="border border-border bg-card p-5"><h2 className="stencil text-xl">Allowed domains</h2><form action={addAllowedFriendDomain} className="mt-5 flex gap-2"><input required name="domain" placeholder="example.com" className="min-w-0 flex-1 border border-input bg-background px-3 py-2 text-sm text-foreground" /><button className="border border-border px-4 py-2 text-sm hover:border-primary">Add domain</button></form><ul className="mt-5 divide-y divide-border border-y border-border">{(domains ?? []).map((item) => <li key={item.domain} className="flex items-center justify-between gap-3 py-3 text-sm"><span className="text-foreground">{item.domain}</span><form action={async () => { 'use server'; await removeAllowedFriendDomain(item.domain) }}><button className="text-xs text-muted-foreground underline hover:text-destructive">Remove</button></form></li>)}{domains?.length === 0 && <li className="py-4 text-sm text-muted-foreground">No domains added yet.</li>}</ul></section></main>
}
